kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: calico-controller
  namespace: kube-system
spec:
  replicas: 1
  revisionHistoryLimit: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        k8s-app: calico-controller
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      serviceAccountName: calico-controller
      containers:
      - name: calico-controller
        image: registry.joinverse.com/calico-controller:{{ DOCKER_IMAGE_TAG }}
        env:
        - name: ETCD_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              key: etcd_endpoints
              name: calico-config
        resources:
          requests:
            cpu: 10m
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - key: CriticalAddonsOnly
        operator: Exists

