apiVersion: v1
kind: ServiceAccount
metadata:
  name: calico-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: calico-controller
rules:
- apiGroups:
  - calico.verse.me
  resources:
  - calicopolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: calico-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: calico-controller
subjects:
- kind: ServiceAccount
  name: calico-controller
  namespace: kube-system
